volumes:
  data:
  mydb:
  tom:
networks:
  frontend:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.21.0/24
  backend:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.22.0/24
services:
  web:
    image: httpd
    ports:
      - 81:80
    volumes:
      - data:/usr/local/apache2/htdocs
    networks:
      - frontend
    depends_on:
         - app

  db:
    image: mysql
    ports:
      - 3366:3306
    environment:
      MYSQL_ROOT_PASSWORD: redhat
    volumes:
      - mydb:/var/lib/mysql
    networks:
      - backend

  app:
    image: tomcat
    ports:
      - 8081:8080
    volumes:
      - tom:/usr/local/tomcat
    depends_on:
        - db
    networks:
      - backend
      - frontend
